services:
  - type: web
    name: toolhive-backend
    runtime: node
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: ADMIN_USERNAME
        value: toolhive@9698
      - key: ADMIN_PASSWORD
        value: ToolHive@9698
      - key: CLIENT_URL
        sync: false

  - type: web
    name: toolhive-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        sync: false
