module.exports = {
  AF: 'Afghanistan', AL: 'Albania', DZ: 'Algeria', AR: 'Argentina',
  AU: 'Australia', AT: 'Austria', BD: 'Bangladesh', BE: 'Belgium',
  BR: 'Brazil', CA: 'Canada', CN: 'China', CO: 'Colombia',
  HR: 'Croatia', CZ: 'Czech Republic', DK: 'Denmark', EG: 'Egypt',
  ET: 'Ethiopia', FI: 'Finland', FR: 'France', DE: 'Germany',
  GH: 'Ghana', GR: 'Greece', GT: 'Guatemala', HU: 'Hungary',
  IN: 'India', ID: 'Indonesia', IQ: 'Iraq', IR: 'Iran',
  IE: 'Ireland', IL: 'Israel', IT: 'Italy', JP: 'Japan',
  JO: 'Jordan', KE: 'Kenya', KW: 'Kuwait', LB: 'Lebanon',
  LY: 'Libya', MY: 'Malaysia', MX: 'Mexico', MA: 'Morocco',
  NL: 'Netherlands', NZ: 'New Zealand', NG: 'Nigeria', NO: 'Norway',
  OM: 'Oman', PK: 'Pakistan', PE: 'Peru', PH: 'Philippines',
  PL: 'Poland', PT: 'Portugal', QA: 'Qatar', RO: 'Romania',
  RU: 'Russia', SA: 'Saudi Arabia', SN: 'Senegal', ZA: 'South Africa',
  KR: 'South Korea', ES: 'Spain', LK: 'Sri Lanka', SD: 'Sudan',
  SE: 'Sweden', CH: 'Switzerland', SY: 'Syria', TW: 'Taiwan',
  TZ: 'Tanzania', TH: 'Thailand', TN: 'Tunisia', TR: 'Turkey',
  UG: 'Uganda', UA: 'Ukraine', AE: 'UAE', GB: 'United Kingdom',
  US: 'United States', UZ: 'Uzbekistan', VN: 'Vietnam', YE: 'Yemen',
  ZM: 'Zambia', ZW: 'Zimbabwe',
};
