import { Link } from 'react-router-dom';

const POSTS = [
  { id: 'compress-pdf-online', title: 'How to Compress PDF Online for Free', category: 'PDF Tools', date: 'June 2026', desc: 'Learn how to reduce PDF file size without losing quality using free online tools.', content: `A large PDF file can be difficult to share via email or upload to websites. Compressing a PDF reduces its file size while maintaining readability. ToolHive offers a free PDF compression tool that works entirely in your browser — no upload to any server required.\n\nTo compress a PDF on ToolHive:\n1. Go to PDF Tools and click Compress PDF\n2. Upload your PDF file (up to 50MB)\n3. Click Compress and download your smaller file\n\nOur tool uses advanced compression algorithms to reduce file size by up to 80% in many cases. This is perfect for sending documents via email, uploading to job portals, or sharing on WhatsApp.\n\nWhy compress PDF files? Many email services limit attachments to 10MB or 25MB. Government portals often require documents under 1MB. Compressing your PDF helps you meet these requirements without printing and rescanning.\n\nToolHive's PDF compressor is completely free, requires no login, and processes your file locally in your browser for maximum privacy.` },
  { id: 'convert-image-format', title: 'How to Convert Images Between JPG, PNG and WEBP', category: 'Image Tools', date: 'June 2026', desc: 'A complete guide to converting images between different formats for free online.', content: `Different image formats serve different purposes. JPG is best for photographs, PNG is ideal for images with transparency, and WEBP offers smaller file sizes for web use. Converting between these formats is easy with ToolHive.\n\nHow to convert images on ToolHive:\n1. Go to Image Tools and click Convert Image\n2. Upload your image file\n3. Select your target format (JPG, PNG, or WEBP)\n4. Download your converted image\n\nWhen should you use each format?\n\nJPG — Best for photos and complex images. Smaller file sizes but no transparency support.\n\nPNG — Best for logos, screenshots, and images requiring transparent backgrounds. Higher quality but larger file size.\n\nWEBP — Google's modern format. Best for websites as it offers smaller sizes than both JPG and PNG.\n\nToolHive's image converter is completely free and works on all devices including mobile phones and tablets. No registration required.` },
  { id: 'generate-qr-code', title: 'How to Generate a QR Code for Free', category: 'Web Tools', date: 'June 2026', desc: 'Step by step guide to creating QR codes for websites, text, and contact information.', content: `QR codes are everywhere today — on business cards, restaurant menus, product packaging, and advertisements. Creating your own QR code is completely free with ToolHive.\n\nHow to generate a QR code:\n1. Go to Web & Dev Tools and click QR Code Generator\n2. Enter your URL, text, phone number, or any content\n3. Choose your preferred size\n4. Download the QR code as PNG\n\nCommon uses for QR codes:\n\nBusiness cards — Add a QR code linking to your website or LinkedIn profile\n\nRestaurant menus — Link to your online menu\n\nProduct packaging — Link to product instructions or warranty registration\n\nPayment links — Link to your payment page or UPI ID\n\nEvents — Link to event registration or location on Google Maps\n\nToolHive generates high quality QR codes that can be scanned by any smartphone camera. Our QR codes are completely free to create and download with no watermarks.` },
  { id: 'password-generator-guide', title: 'How to Create Strong Passwords Online', category: 'Security Tools', date: 'June 2026', desc: 'Why strong passwords matter and how to generate them instantly for free.', content: `Weak passwords are the most common cause of account hacking. A strong password should be at least 12 characters long and include uppercase letters, lowercase letters, numbers, and special symbols.\n\nHow to generate a strong password on ToolHive:\n1. Go to Security Tools and click Password Generator\n2. Set your preferred length (we recommend 16 characters)\n3. Select character types to include\n4. Click Generate to create multiple password options\n5. Copy your chosen password\n\nWhat makes a password strong?\n\nLength — Longer passwords are exponentially harder to crack\n\nComplexity — Mix of letters, numbers, and symbols\n\nRandomness — Avoid predictable patterns or personal information\n\nUniqueness — Use a different password for every account\n\nToolHive generates passwords entirely in your browser. We never see or store your passwords. Generate as many as you need completely free without any registration.` },
  { id: 'word-counter-guide', title: 'Free Online Word Counter and Character Counter Tool', category: 'Text Tools', date: 'June 2026', desc: 'Count words, characters, sentences and estimate reading time for any text.', content: `Whether you are writing an essay with a word limit, a tweet with a character limit, or an article with a minimum word count requirement, knowing your exact word and character count is essential.\n\nHow to count words on ToolHive:\n1. Go to Text Tools and click Word Counter\n2. Paste or type your text\n3. See instant counts for words, characters, sentences, and paragraphs\n4. Check estimated reading time\n\nWho needs a word counter?\n\nStudents — Essays and assignments often have strict word limits\n\nFreelancers — Article writers need to meet minimum word counts\n\nSocial media managers — Twitter has 280 character limit, Instagram captions have limits\n\nSEO writers — Meta descriptions should be under 160 characters\n\nToolHive's word counter updates in real time as you type. It shows words, characters with spaces, characters without spaces, sentences, paragraphs, and reading time — all completely free.` },
  { id: 'merge-pdf-guide', title: 'How to Merge Multiple PDF Files into One', category: 'PDF Tools', date: 'June 2026', desc: 'Combine multiple PDF documents into a single file for free online.', content: `Merging PDF files is useful when you need to combine multiple documents into one — like combining a cover letter with a resume, or joining multiple chapters of a document.\n\nHow to merge PDFs on ToolHive:\n1. Go to PDF Tools and click Merge PDF\n2. Upload two or more PDF files\n3. Drag to reorder them if needed\n4. Click Merge and download your combined PDF\n\nCommon reasons to merge PDFs:\n\nJob applications — Combine resume, cover letter, and certificates into one file\n\nLegal documents — Merge contracts and attachments\n\nReports — Combine multiple report sections\n\nInvoices — Merge multiple monthly invoices into one annual document\n\nToolHive's PDF merger supports files up to 50MB each and can combine unlimited PDF files. The entire process happens in your browser with no file uploads to any server, ensuring complete privacy.` },
  { id: 'csv-to-json-guide', title: 'How to Convert CSV to JSON Online for Free', category: 'Office Tools', date: 'June 2026', desc: 'Convert spreadsheet CSV data to JSON format instantly with no coding required.', content: `CSV (Comma Separated Values) and JSON (JavaScript Object Notation) are two of the most common data formats. Developers often need to convert between them when building applications or processing data.\n\nHow to convert CSV to JSON on ToolHive:\n1. Go to Office Tools and click CSV to JSON\n2. Upload your CSV file or paste CSV content\n3. Preview your converted JSON data\n4. Copy or download the JSON file\n\nWhen do you need CSV to JSON conversion?\n\nWeb development — JSON is the standard format for web APIs\n\nData processing — Many programming languages work better with JSON\n\nDatabase import — Some databases accept JSON format\n\nAPI integration — When sending data to third party services\n\nToolHive converts your CSV data instantly with no file size limits for text content. Your data never leaves your browser, ensuring complete privacy and security.` },
  { id: 'image-compressor-guide', title: 'How to Compress Images Without Losing Quality', category: 'Image Tools', date: 'June 2026', desc: 'Reduce image file sizes for faster websites and easier sharing while keeping quality.', content: `Large image files slow down websites, consume mobile data, and are difficult to share. Compressing images reduces file size while maintaining acceptable visual quality.\n\nHow to compress images on ToolHive:\n1. Go to Image Tools and click Compress Image\n2. Upload your image (JPG, PNG, or WEBP)\n3. Adjust quality slider to your preference\n4. Download your compressed image\n\nWhy compress images?\n\nWebsite speed — Smaller images load faster, improving user experience and SEO rankings\n\nEmail attachments — Compressed images are easier to send via email\n\nWhatsApp sharing — Reduce image size for faster sharing\n\nStorage — Save space on your device or cloud storage\n\nSocial media — Faster uploads to Instagram, Facebook, and Twitter\n\nToolHive can reduce image file sizes by up to 90% depending on the original image and quality settings. Our tool is completely free with no watermarks added to your images.` },
  { id: 'json-formatter-guide', title: 'How to Format and Validate JSON Online', category: 'Web Tools', date: 'June 2026', desc: 'Beautify minified JSON and check for syntax errors instantly for free.', content: `JSON is the most widely used data format in web development. Poorly formatted or invalid JSON can cause errors in applications and APIs. ToolHive's JSON formatter helps you beautify and validate JSON instantly.\n\nHow to format JSON on ToolHive:\n1. Go to Web & Dev Tools and click JSON Formatter\n2. Paste your JSON data\n3. Click Format to beautify or Minify to compress\n4. Copy the result\n\nCommon JSON problems solved:\n\nMinified JSON — Hard to read single line JSON converted to readable indented format\n\nSyntax errors — Instantly identify missing brackets, commas, or quotes\n\nAPI responses — Format raw API responses for easy reading and debugging\n\nConfiguration files — Validate JSON config files before deployment\n\nToolHive's JSON formatter works with JSON of any size and complexity. It highlights syntax errors with helpful messages so you can fix problems quickly.` },
  { id: 'digital-signature-guide', title: 'How to Create a Free Digital Signature Online', category: 'Web Tools', date: 'June 2026', desc: 'Draw and download your digital signature for documents and contracts for free.', content: `A digital signature is increasingly accepted for contracts, forms, and official documents. Creating a professional digital signature is easy and free with ToolHive.\n\nHow to create a digital signature on ToolHive:\n1. Go to Web & Dev Tools and click Digital Signature\n2. Choose your pen color and size\n3. Draw your signature using mouse or touchscreen\n4. Download as PNG image\n\nHow to use your digital signature:\n\nPDF documents — Insert your signature image into PDF contracts\n\nWord documents — Add your signature to Word files\n\nEmail — Attach signature to formal emails\n\nOnline forms — Upload signature image where required\n\nToolHive's signature tool works perfectly on mobile phones and tablets using your finger, or on desktop using your mouse. Your signature is never stored on our servers — it exists only in your browser during creation.` },
];

export default function Blog() {
  return (
    <div className="animate-fade-up space-y-8">
      <div className="text-center py-6">
        <h1 className="text-3xl font-bold text-slate-900 dark:text-white mb-2">ToolHive Blog</h1>
        <p className="text-gray-500 dark:text-gray-400">Guides and tutorials for all our free online tools</p>
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-5">
        {POSTS.map(post => (
          <Link key={post.id} to={`/blog/${post.id}`}
            className="tool-card flex flex-col">
            <span className="text-xs text-amber-600 font-semibold mb-2">{post.category}</span>
            <h2 className="font-bold text-slate-900 dark:text-white mb-2 leading-snug hover:text-amber-600 transition-colors">{post.title}</h2>
            <p className="text-sm text-gray-400 leading-relaxed flex-1">{post.desc}</p>
            <div className="flex items-center justify-between mt-4 pt-3 border-t border-gray-100 dark:border-slate-800">
              <span className="text-xs text-gray-400">{post.date}</span>
              <span className="text-xs text-amber-600 font-medium">Read more →</span>
            </div>
          </Link>
        ))}
      </div>
    </div>
  );
}

export { POSTS };
